# Generated by Django 3.2.5 on 2021-07-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
