# Generated by Django 3.2.5 on 2021-07-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_alter_contactus_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='type',
            new_name='currency_type',
        ),
    ]
